<a href="https://colab.research.google.com/github/rattakan06/rattakan06-229352-StatisticalLearning-or-Statistical-Learning-Labs./blob/main/lab08_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [ ]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
a = torch.tensor(1)
b = torch.tensor(2)

### Convert a tensor to scalar

In [ ]:
c = b.item()

### Creating 2D tensor

In [ ]:
a = torch.tensor([[1,2],[5,6]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [ ]:
b = a.numpy()
print(b)

[[1 2]
 [5 6]]


### Convert from numpy array to tensor

In [ ]:
c = torch.from_numpy(b)
print(c)

tensor([[1, 2],
        [5, 6]])


## PyTorch and GPU

check if GPU is available

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [ ]:
c.device

device(type='cpu')

In [ ]:
d = c.cuda()
d

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [ ]:
d.device.  #เช็คว่าอยู่ใน cpu หรือ gpu

device(type='cuda', index=0)

In [ ]:
c+d # ไม่ได้นะ

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
e = d.cpu()
e.numpy()

array([[1, 2],
       [5, 6]])

## Basic operations

In [ ]:
e *2

tensor([[ 2,  4],
        [10, 12]])

In [ ]:
e-2

tensor([[-1,  0],
        [ 3,  4]])

In [ ]:
e * np.array([1,2])

/tmp/ipython-input-1032887840.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  e * np.array([1,2])


tensor([[ 1,  4],
        [ 5, 12]])

In [ ]:
d-2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [ ]:
d.cpu() * np.array([1,2])

/tmp/ipython-input-3504366457.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  d.cpu() * np.array([1,2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [ ]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[5,6],[7,8]])
torch.matmul(A,B)

tensor([[19, 22],
        [43, 50]])

In [ ]:
torch.mm(A,B)

tensor([[19, 22],
        [43, 50]])

In [ ]:
A @ B #จำง่าย

tensor([[19, 22],
        [43, 50]])

In [ ]:
A.t()

tensor([[1, 3],
        [2, 4]])

In [ ]:
a =torch.zeros(1,2,3)

### Matrix transpose

In [ ]:
A.t()

tensor([[1, 3],
        [2, 4]])

## Creating a specific type of tensor

In [ ]:
a = torch.zeros(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
b = torch.ones(2,3)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
I = torch.eye(3)
print(I)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
R1 = torch.rand(2,3) #สุ่มจาการแจกแจง ยูนิฟอร์ม ทุกค่าอยู่ระหว่าง 0-1 ทุกตัวมีโอกาสถูกสุ่มเ่ากัน
R1

tensor([[0.4099, 0.9652, 0.7953],
        [0.4047, 0.0685, 0.1304]])

In [ ]:
R2 = torch.randn(2,3) #สุ่มจากการแจกแจงปกติ
R2

tensor([[ 0.4238, -0.7131,  0.2756],
        [-1.4214,  0.6852, -1.0067]])

In [ ]:
a = torch.arange(10)
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Tensor's shape

In [ ]:
a.shape

torch.Size([2, 3])

In [ ]:
a.size()

torch.Size([2, 3])

### Checking the shape of a tensor

In [ ]:
u = torch.arange(6)
u

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
w = u.view(2,3)
w

tensor([[0, 1, 2],
        [3, 4, 5]])

### Changing the shape of a tensor

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [ ]:
a = torch.arange(4)
b = torch.arange(4) + 1
c = torch.stack([a,b],axis = 0)
d = torch.stack([a,b],axis = 1)
print(c)
print(d)

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])
tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])


In [ ]:
# concatenate
e = torch.cat([a,b],axis = 0)
print(e)

tensor([0, 1, 2, 3, 1, 2, 3, 4])


### Squeezing a tensor (removing an extra dimension)

In [ ]:
A = torch.zeros(2,1,3)
A

tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])

In [ ]:
A = torch.zeros(2,1,3)
B = A.squeeze()
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
# H.shape = (6, )
c = B.unsqueeze(0)
c.shape

torch.Size([1, 2, 3])

## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [ ]:
#inverse_matrix
A = torch.tensor([[1,2],[3,4]])
A_inv = torch.inverse(A)


RuntimeError: linalg.inv: Expected a floating point or complex tensor as input. Got Long

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [ ]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [ ]:
X = torch.randn(200,7)
XF = torch.ones(200,1)
X = torch.cat([XF,X],axis = 1)
b = torch.ones(8,1)
e = torch.randn(200,1)

In [ ]:
y = X @ b + e
b_hat = torch.inverse(X.T @ X) @ X.T @ y
y_hat = X @ b_hat
MSE = torch.mean((y - y_hat)**2)
print(MSE)

tensor(0.7624)
